<script>
	import logo from '$lib/assets/logo.png';
	import NavMenu from '$lib/components/layoutCompnents/Header/NavMenu.svelte';

</script>

<header class="animate-header z-10 mx-auto mt-24 w-[80vw] rounded-md bg-transparent">
	<div class="mx-auto max-w-5xl px-4">
		<div class="flex h-auto flex-col items-center justify-between py-4 md:h-16 md:flex-row md:py-0">
			<div class="flex flex-col items-center md:items-start">
				<a href="/ADC-5" class="flex flex-col items-center">
					<img
						src={logo}
						alt="Logo"
						class="text-focus-in mx-auto mb-4 h-auto w-40 duration-200 hover:scale-105 md:mx-0 md:mb-0 md:w-50"
					/>
					<p class="font-semibold text-red-100 uppercase drop-shadow-lg text-focus-in">Gravity Grit Glory</p>
				</a>
				<!-- svelte-ignore a11y_consider_explicit_label -->
				<button class="mb-4 text-gray-900 focus:outline-none md:hidden">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						class="h-6 w-6"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M4 6h16M4 12h16M4 18h16"
						/>
					</svg>
				</button>
			</div>
			<NavMenu />
		</div>
	</div>
	<hr class="my-5 border-1 border-white opacity-50" />
</header>

<style>
	.animate-header {
		-webkit-animation: slide-in-left 1.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
		animation: slide-in-left 1.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
	}

	@-webkit-keyframes slide-in-left {
		0% {
			-webkit-transform: translateX(-900px);
			transform: translateX(-900px);
			opacity: 0;
		}
		100% {
			-webkit-transform: translateX(0);
			transform: translateX(0);
			opacity: 0.8;
		}
	}
	@keyframes slide-in-left {
		0% {
			-webkit-transform: translateX(-1000px);
			transform: translateX(-1000px);
			opacity: 0;
		}
		100% {
			-webkit-transform: translateX(0);
			transform: translateX(0);
			opacity: 0.8;
		}
	}

	.text-focus-in {
		-webkit-animation: text-focus-in 1.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
		animation: text-focus-in 1.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
	}

	/* ----------------------------------------------
  * Generated by Animista on 2025-3-2 23:16:56
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

	/**
  * ----------------------------------------
  * animation text-focus-in
  * ----------------------------------------
  */
	@-webkit-keyframes text-focus-in {
		0% {
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}
		100% {
			-webkit-filter: blur(0px);
			filter: blur(0px);
			opacity: 1;
		}
	}
	@keyframes text-focus-in {
		0% {
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}
		100% {
			-webkit-filter: blur(0px);
			filter: blur(0px);
			opacity: 1;
		}
	}
</style>
