<script>
    import SocialLinks from "$lib/components/shared/SocialLinks.svelte";
</script>

    <div
        class="w-fit p-10 mx-auto grid grid-row-auto text-center gap-12 items-center md:mt-16 rounded-3xl justify-center"
    >
        <div class="roll-in-right">
            <h2
                class="text-4xl font-extrabold text-white text-flicker-in-glow"
            >
                5th & 6th April 2025
            </h2>
        </div>
        <div class="roll-in-left flex flex-col gap-5 items-center justify-between">
            <p class="text-xl font-bold text-white text-flicker-in-glow">
                <i class="fa-solid fa-location-dot text-xl" style="color: #f57d3d;"></i> &nbsp; Monkey Temple Trail, Borbari
            </p>
            <SocialLinks />
        </div>
        <div>
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSeJ_LrIdhKr4-rJoYqGnsreCZOQJWqqKlqCEQygFJSz4jiq4w/viewform" target="_blank"
                class="relative inline-block p-px font-semibold leading-6 text-white no-underline bg-gray-800 shadow-2xl cursor-pointer group rounded-xl shadow-zinc-900"
                ><span class="absolute inset-0 overflow-hidden rounded-xl"
                    ><span
                        class="absolute inset-0 rounded-xl bg-[image:radial-gradient(75%_100%_at_50%_0%,rgba(56,189,248,0.6)_0%,rgba(56,189,248,0)_75%)] opacity-0 transition-opacity duration-500 group-hover:opacity-100 has-shadow boldest shadow-white"
                    >
                    </span>
                </span>
                <div
                    class="relative z-10 flex items-center px-6 py-3 space-x-2 rounded-xl bg-gray-950/50 ring-1 ring-white/10"
                >
                    <span> Register now </span>
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                        aria-hidden="true"
                        data-slot="icon"
                        class="w-6 h-6"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z"
                            clip-rule="evenodd"></path>
                    </svg>
                </div>
                <span
                    class="absolute -bottom-0 left-[1.125rem] h-px w-[calc(100%-2.25rem)] bg-gradient-to-r from-emerald-400/60 via-gray-400/90 to-emerald-400/0 transition-opacity duration-500 group-hover:opacity-40"
                ></span>
            </a>
        </div>
    </div>

<style>
    .text-flicker-in-glow {
        -webkit-animation: text-flicker-in-glow 0.3s linear both;
        animation: text-flicker-in-glow 0.3s linear both;
    }

    /* ----------------------------------------------
* Generated by Animista on 2025-3-3 1:19:55
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

    /**
* ----------------------------------------
* animation text-flicker-in-glow
* ----------------------------------------
*/
    @-webkit-keyframes text-flicker-in-glow {
        0% {
            opacity: 0;
        }
        10% {
            opacity: 0;
            text-shadow: none;
        }
        10.1% {
            opacity: 1;
            text-shadow: none;
        }
        10.2% {
            opacity: 0;
            text-shadow: none;
        }
        20% {
            opacity: 0;
            text-shadow: none;
        }
        20.1% {
            opacity: 1;
            text-shadow: 0 0 30px rgba(255, 255, 255, 0.25);
        }
        20.6% {
            opacity: 0;
            text-shadow: none;
        }
        30% {
            opacity: 0;
            text-shadow: none;
        }
        30.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        30.5% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        30.6% {
            opacity: 0;
            text-shadow: none;
        }
        45% {
            opacity: 0;
            text-shadow: none;
        }
        45.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        50% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        55% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        55.1% {
            opacity: 0;
            text-shadow: none;
        }
        57% {
            opacity: 0;
            text-shadow: none;
        }
        57.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35);
        }
        60% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35);
        }
        60.1% {
            opacity: 0;
            text-shadow: none;
        }
        65% {
            opacity: 0;
            text-shadow: none;
        }
        65.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        75% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        75.1% {
            opacity: 0;
            text-shadow: none;
        }
        77% {
            opacity: 0;
            text-shadow: none;
        }
        77.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.4),
                0 0 110px rgba(255, 255, 255, 0.2),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        85% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.4),
                0 0 110px rgba(255, 255, 255, 0.2),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        85.1% {
            opacity: 0;
            text-shadow: none;
        }
        86% {
            opacity: 0;
            text-shadow: none;
        }
        86.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.6),
                0 0 60px rgba(255, 255, 255, 0.45),
                0 0 110px rgba(255, 255, 255, 0.25),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        100% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.6),
                0 0 60px rgba(255, 255, 255, 0.45),
                0 0 110px rgba(255, 255, 255, 0.25),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
    }
    @keyframes text-flicker-in-glow {
        0% {
            opacity: 0;
        }
        10% {
            opacity: 0;
            text-shadow: none;
        }
        10.1% {
            opacity: 1;
            text-shadow: none;
        }
        10.2% {
            opacity: 0;
            text-shadow: none;
        }
        20% {
            opacity: 0;
            text-shadow: none;
        }
        20.1% {
            opacity: 1;
            text-shadow: 0 0 30px rgba(255, 255, 255, 0.25);
        }
        20.6% {
            opacity: 0;
            text-shadow: none;
        }
        30% {
            opacity: 0;
            text-shadow: none;
        }
        30.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        30.5% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        30.6% {
            opacity: 0;
            text-shadow: none;
        }
        45% {
            opacity: 0;
            text-shadow: none;
        }
        45.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        50% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        55% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.45),
                0 0 60px rgba(255, 255, 255, 0.25);
        }
        55.1% {
            opacity: 0;
            text-shadow: none;
        }
        57% {
            opacity: 0;
            text-shadow: none;
        }
        57.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35);
        }
        60% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35);
        }
        60.1% {
            opacity: 0;
            text-shadow: none;
        }
        65% {
            opacity: 0;
            text-shadow: none;
        }
        65.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        75% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.35),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        75.1% {
            opacity: 0;
            text-shadow: none;
        }
        77% {
            opacity: 0;
            text-shadow: none;
        }
        77.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.4),
                0 0 110px rgba(255, 255, 255, 0.2),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        85% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.55),
                0 0 60px rgba(255, 255, 255, 0.4),
                0 0 110px rgba(255, 255, 255, 0.2),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        85.1% {
            opacity: 0;
            text-shadow: none;
        }
        86% {
            opacity: 0;
            text-shadow: none;
        }
        86.1% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.6),
                0 0 60px rgba(255, 255, 255, 0.45),
                0 0 110px rgba(255, 255, 255, 0.25),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
        100% {
            opacity: 1;
            text-shadow:
                0 0 30px rgba(255, 255, 255, 0.6),
                0 0 60px rgba(255, 255, 255, 0.45),
                0 0 110px rgba(255, 255, 255, 0.25),
                0 0 100px rgba(255, 255, 255, 0.1);
        }
    }

    /* ----------------------------------------------
* Generated by Animista on 2025-3-3 1:55:23
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */
    .roll-in-right {
        -webkit-animation: roll-in-right 2s ease-out both;
        animation: roll-in-right 2s ease-out both;
    }
    /**
* ----------------------------------------
* animation roll-in-right
* ----------------------------------------
*/
    @-webkit-keyframes roll-in-right {
        0% {
            -webkit-transform: translateX(800px) rotate(540deg);
            transform: translateX(800px) rotate(540deg);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0) rotate(0deg);
            transform: translateX(0) rotate(0deg);
            opacity: 1;
        }
    }
    @keyframes roll-in-right {
        0% {
            -webkit-transform: translateX(800px) rotate(540deg);
            transform: translateX(800px) rotate(540deg);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0) rotate(0deg);
            transform: translateX(0) rotate(0deg);
            opacity: 1;
        }
    }
    .roll-in-left {
        -webkit-animation: roll-in-left 2s ease-out both;
        animation: roll-in-left 2s ease-out both;
    }
    /* ----------------------------------------------
* Generated by Animista on 2025-3-3 1:56:43
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

    /**
* ----------------------------------------
* animation roll-in-left
* ----------------------------------------
*/
    @-webkit-keyframes roll-in-left {
        0% {
            -webkit-transform: translateX(-800px) rotate(-540deg);
            transform: translateX(-800px) rotate(-540deg);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0) rotate(0deg);
            transform: translateX(0) rotate(0deg);
            opacity: 1;
        }
    }
    @keyframes roll-in-left {
        0% {
            -webkit-transform: translateX(-800px) rotate(-540deg);
            transform: translateX(-800px) rotate(-540deg);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0) rotate(0deg);
            transform: translateX(0) rotate(0deg);
            opacity: 1;
        }
    }
</style>